// <auto-generated />
namespace TennisScheduler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class dog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dog));
        
        string IMigrationMetadata.Id
        {
            get { return "201502201732341_dog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
